FROM alpine:latest
WORKDIR /app
RUN apk update && apk upgrade
RUN apk add git bash bash-doc bash-completion coreutils ncurses
RUN git clone https://github.com/offensive-security/exploitdb.git /opt/exploit-database
RUN ln -sf /opt/exploit-database/searchsploit /usr/local/bin/searchsploit
ENTRYPOINT ["searchsploit"]